In [2]:
import numpy as np

In [5]:
np.arange(2,51,3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50])

In [6]:
lst1=[]
lst2=[]
for i in range(0, 5): 
    ele=int(input()) 
    lst1.append(ele)
for i in range(0, 5): 
    ele=int(input()) 
    lst2.append(ele)
arr1=np.array(lst1) 
arr2=np.array(lst2)
arr=np.concatenate((arr1,arr2))
print(arr)
arr.sort()
print(arr)

10
2
67
3
9
6
0
3
56
38
[10  2 67  3  9  6  0  3 56 38]
[ 0  2  3  3  6  9 10 38 56 67]


In [7]:
arr.shape

(10,)

In [10]:
arr1=np.array([[1,2,3],[7,8,9],[2,3,4]])
arr1.shape

(3, 3)

In [11]:
arr1.size

9

In [12]:
arr.size

10

In [27]:
import numpy as np
a = np.array([2, 4])
b = np.expand_dims(a, axis=0)
b
b.shape



(1, 2)

In [21]:
arr1=np.random.rand(2,2)
arr2=np.random.rand(4,4)
print(np.hsplit(arr1, 2))
print(np.vsplit(arr1, 2))
print(np.hsplit(arr2, 2))
print(np.vsplit(arr2, 2))

[array([[0.26269018],
       [0.10453097]]), array([[0.23349342],
       [0.04318255]])]
[array([[0.26269018, 0.23349342]]), array([[0.10453097, 0.04318255]])]
[array([[0.73454738, 0.25821183],
       [0.48345565, 0.74301737],
       [0.01214849, 0.55264575],
       [0.24732955, 0.48212348]]), array([[0.40750254, 0.60540467],
       [0.59067544, 0.13515849],
       [0.54355097, 0.40752637],
       [0.39183303, 0.91267515]])]
[array([[0.73454738, 0.25821183, 0.40750254, 0.60540467],
       [0.48345565, 0.74301737, 0.59067544, 0.13515849]]), array([[0.01214849, 0.55264575, 0.54355097, 0.40752637],
       [0.24732955, 0.48212348, 0.39183303, 0.91267515]])]


In [23]:
a = np.array([10,10,20,10,20,20,20,30, 30,50,40,40])
elements, counts = np.unique(a, return_counts=True)
print(np.asarray((unique_elements, counts_elements)))

[[10 20 30 40 50]
 [ 3  4  2  2  1]]
